export const PERMISSIONS = {
  
  ROLE_VIEW: 'ROLE_VIEW_LIST',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_EDIT: 'ROLE_EDIT',
  ROLE_DELETE: 'ROLE_DELETE',

  
  USER_VIEW: 'USER_VIEW_LIST',
  USER_CREATE: 'USER_CREATE',
  USER_EDIT_MYSELF: 'USER_EDIT_MYSELF',
  USER_EDIT_OTHERS: 'USER_EDIT_OTHERS',
  USER_EDIT_ROLES: 'USER_EDIT_ROLES',
  USER_DELETE: 'USER_DELETE',

  
  FOOD_VIEW: 'FOOD_VIEW_LIST',
  FOOD_CREATE: 'FOOD_CREATE',
  FOOD_EDIT: 'FOOD_EDIT',
  FOOD_DELETE: 'FOOD_DELETE',

  
  PRODUCT_VIEW: 'PRODUCT_VIEW_LIST',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_EDIT: 'PRODUCT_EDIT',
  PRODUCT_EDIT_INGREDIENTS: 'PRODUCT_EDIT_INGREDIENTS',
  PRODUCT_DELETE: 'PRODUCT_DELETE',

  
  TABLE_VIEW: 'TABLE_VIEW_LIST',
  TABLE_CREATE: 'TABLE_CREATE',
  TABLE_EDIT: 'TABLE_EDIT',
  TABLE_DELETE: 'TABLE_DELETE',

  
  RESERVATION_VIEW: 'RESERVATION_VIEW_LIST',
  RESERVATION_CREATE: 'RESERVATION_CREATE',
  RESERVATION_EDIT: 'RESERVATION_EDIT',
  RESERVATION_DELETE: 'RESERVATION_DELETE',

  
  ORDER_VIEW: 'ORDER_VIEW_LIST',
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_BAR_VIEW: 'ORDER_BAR_VIEW_LIST',
  ORDER_DINING_VIEW: 'ORDER_DINING_VIEW_LIST',
};
